SELECT 'Sale' AS t, COUNT(*) AS n, CAST(MAX(InvoiceDate) AS VARCHAR(20)) AS mx FROM saller.SaleInvoiceHeader;
OUTPUT TO 'C:\\MY ERPS\\import\\fmye\\_a_sale.txt' FORMAT TEXT QUOTES OFF;
SELECT CAST(InvoiceDate AS VARCHAR(20)) AS d, COUNT(*) AS n FROM saller.SaleInvoiceHeader WHERE InvoiceDate >= DATE('2026-08-06') GROUP BY InvoiceDate ORDER BY 1;
OUTPUT TO 'C:\\MY ERPS\\import\\fmye\\_a_sale_d.txt' FORMAT TEXT QUOTES OFF;
SELECT 'Purch' AS t, COUNT(*) AS n, CAST(MAX(PurchaseInvoiceDate) AS VARCHAR(20)) AS mx FROM saller.PurchaseHeader;
OUTPUT TO 'C:\\MY ERPS\\import\\fmye\\_a_purch.txt' FORMAT TEXT QUOTES OFF;
SELECT CAST(PurchaseInvoiceDate AS VARCHAR(20)) AS d, COUNT(*) AS n FROM saller.PurchaseHeader WHERE PurchaseInvoiceDate >= DATE('2026-08-06') GROUP BY PurchaseInvoiceDate ORDER BY 1;
OUTPUT TO 'C:\\MY ERPS\\import\\fmye\\_a_purch_d.txt' FORMAT TEXT QUOTES OFF;
SELECT 'Vouch' AS t, COUNT(*) AS n, CAST(MAX(VoucherDate) AS VARCHAR(20)) AS mx FROM saller.Voucher;
OUTPUT TO 'C:\\MY ERPS\\import\\fmye\\_a_vouch.txt' FORMAT TEXT QUOTES OFF;
SELECT CAST(VoucherDate AS VARCHAR(20)) AS d, COUNT(*) AS n FROM saller.Voucher WHERE VoucherDate >= DATE('2026-08-06') GROUP BY VoucherDate ORDER BY 1;
OUTPUT TO 'C:\\MY ERPS\\import\\fmye\\_a_vouch_d.txt' FORMAT TEXT QUOTES OFF;
SELECT CAST(VoucherDate AS VARCHAR(20)) AS d, VoucherType AS vt, COUNT(*) AS n FROM saller.Voucher WHERE VoucherDate >= DATE('2026-08-06') GROUP BY VoucherDate, VoucherType ORDER BY 1,2;
OUTPUT TO 'C:\\MY ERPS\\import\\fmye\\_a_vouch_t.txt' FORMAT TEXT QUOTES OFF;
SELECT 'Sr' AS t, COUNT(*) AS n, CAST(MAX(SrDate) AS VARCHAR(20)) AS mx FROM saller.SrHeader;
OUTPUT TO 'C:\\MY ERPS\\import\\fmye\\_a_sr.txt' FORMAT TEXT QUOTES OFF;
SELECT CAST(SrDate AS VARCHAR(20)) AS d, COUNT(*) AS n FROM saller.SrHeader WHERE SrDate >= DATE('2026-08-01') GROUP BY SrDate ORDER BY 1;
OUTPUT TO 'C:\\MY ERPS\\import\\fmye\\_a_sr_d.txt' FORMAT TEXT QUOTES OFF;
SELECT 'Pr' AS t, COUNT(*) AS n, CAST(MAX(PrDate) AS VARCHAR(20)) AS mx FROM saller.PrHeader;
OUTPUT TO 'C:\\MY ERPS\\import\\fmye\\_a_pr.txt' FORMAT TEXT QUOTES OFF;
SELECT CAST(PrDate AS VARCHAR(20)) AS d, COUNT(*) AS n FROM saller.PrHeader WHERE PrDate >= DATE('2026-08-01') GROUP BY PrDate ORDER BY 1;
OUTPUT TO 'C:\\MY ERPS\\import\\fmye\\_a_pr_d.txt' FORMAT TEXT QUOTES OFF;
