"""Technical debt scanner — evidence for TECHNICAL_DEBT_REPORT.md"""

from __future__ import annotations

import os
import re
import json
from pathlib import Path
from collections import defaultdict

ROOT = Path(__file__).resolve().parents[1]


def scan_ui_db_calls() -> dict:
    counts = defaultdict(int)
    files = []
    patterns = [
        re.compile(r"\bdb\.(get_|add_|save_|update_|delete_|search_|post_)"),
        re.compile(r"\bdb_v3\."),
        re.compile(r"from db_v3 import"),
        re.compile(r"import database"),
    ]
    for path in (ROOT / "erp_ui").rglob("*.py"):
        text = path.read_text(encoding="utf-8", errors="ignore")
        hits = sum(len(p.findall(text)) for p in patterns)
        if hits:
            counts[str(path.relative_to(ROOT))] = hits
            files.append({"file": str(path.relative_to(ROOT)), "db_calls": hits})
    return {"total_calls": sum(counts.values()), "files": sorted(files, key=lambda x: -x["db_calls"])[:40]}


def scan_db_v3_functions() -> dict:
    text = (ROOT / "db_v3.py").read_text(encoding="utf-8", errors="ignore")
    funcs = re.findall(r"^def (\w+)", text, re.M)
    return {"function_count": len(funcs), "functions": funcs[:50], "total_lines": text.count("\n")}


def scan_database_functions() -> dict:
    text = (ROOT / "database.py").read_text(encoding="utf-8", errors="ignore")
    funcs = re.findall(r"^def (\w+)", text, re.M)
    return {"function_count": len(funcs), "total_lines": text.count("\n")}


def scan_application_coverage() -> dict:
    app_text = ""
    for p in (ROOT / "application").rglob("*.py"):
        app_text += p.read_text(encoding="utf-8", errors="ignore")
    app_funcs = len(re.findall(r"^def |^class ", app_text, re.M))
    ui = scan_ui_db_calls()
    return {
        "application_symbols": app_funcs,
        "ui_direct_db_calls": ui["total_calls"],
        "migration_pct_estimate": round(max(0, 100 - ui["total_calls"] / 10), 1),
    }


def to_markdown() -> str:
    ui = scan_ui_db_calls()
    v3 = scan_db_v3_functions()
    dba = scan_database_functions()
    app = scan_application_coverage()
    lines = [
        "# Technical Debt Report — V17.0",
        "",
        "**Generated by:** `tools/debt_scanner.py` (automated evidence)",
        "",
        "## Summary",
        "",
        f"| Metric | Value |",
        f"|--------|------:|",
        f"| `db_v3.py` functions | {v3['function_count']} |",
        f"| `db_v3.py` lines | {v3['total_lines']} |",
        f"| `database.py` functions | {dba['function_count']} |",
        f"| `database.py` lines | {dba['total_lines']} |",
        f"| Direct DB calls in `erp_ui/` | {ui['total_calls']} |",
        f"| Application layer symbols | {app['application_symbols']} |",
        "",
        "## Status",
        "",
        "Business logic migration to `application/` is **in progress**. V17 establishes:",
        "- `application/tenant.py` — tenant enforcement",
        "- `application/rules/engine.py` — rule engine",
        "- `application/workflows/designer.py` — workflow runtime",
        "- `application/scripts/sandbox.py` — script engine",
        "- `application/services.py` — service facades",
        "",
        "**Remaining debt:** `db_v3.py` and `database.py` still host GL posting, invoice workflow, and master CRUD.",
        "",
        "## Top UI files with direct database access",
        "",
        "| File | DB call patterns |",
        "|------|----------------:|",
    ]
    for f in ui["files"][:25]:
        lines.append(f"| `{f['file']}` | {f['db_calls']} |")
    lines += [
        "",
        "## Migration priority (P0 → P2)",
        "",
        "1. **P0** — Sales/purchase invoice approve+post → `application/sales.py`, `application/purchase.py`",
        "2. **P1** — Finance GL → `application/finance.py`",
        "3. **P1** — HR pages → `application/hr.py`",
        "4. **P2** — Reports (read-only facades)",
        "",
        "## Rule",
        "",
        "No new business rules in `erp_ui/` or `db_v3.py`. All new logic → `application/`.",
    ]
    return "\n".join(lines)


if __name__ == "__main__":
    print(to_markdown())
