"""Professional print formats for ERP documents."""

from __future__ import annotations

from html import escape
from datetime import datetime

from application import data_gateway as db
from erp_ui.report_print import (
    get_company_info,
    PRINT_CSS_PORTRAIT_FULL,
    PRINT_CSS_PORTRAIT_HALF,
    _now_str,
    print_company_header_scope,
    use_print_company_header_checkbox,
    company_letterhead_html,
)
from erp_ui.helpers import fmt_datetime, fmt_datetime_from_record


def _so_status_display(status) -> str:
    """Sales order status for print/UI: open→Active, partial→Partial."""
    try:
        from erp_ui.invoice_status_ui import status_label
        return status_label(status or "open")
    except Exception:
        raw = str(status or "open").strip().lower()
        return {"open": "Active", "partial": "Partial"}.get(
            raw, raw.replace("_", " ").title() or "—"
        )


# Reports that print with standard cash-book signature lines
CASH_TRANSACTION_REPORTS = frozenset({"Cash Book", "Bank Book"})

PRINT_STYLE_SYSTEM = "system"
PRINT_STYLE_CASH = "cash"
PRINT_STYLE_POSTED = "posted"


def amount_in_words(amount) -> str:
    """Convert number to Pakistani/Indian Rupees words (e.g. 1,25,430.50)."""
    try:
        n = float(amount or 0)
    except (TypeError, ValueError):
        return ""
    if n < 0:
        return "Minus " + amount_in_words(-n)

    ones = (
        "", "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine",
        "Ten", "Eleven", "Twelve", "Thirteen", "Fourteen", "Fifteen", "Sixteen",
        "Seventeen", "Eighteen", "Nineteen",
    )
    tens = ("", "", "Twenty", "Thirty", "Forty", "Fifty", "Sixty", "Seventy", "Eighty", "Ninety")

    def _under_thousand(x: int) -> str:
        x = int(x)
        if x == 0:
            return ""
        if x < 20:
            return ones[x]
        if x < 100:
            return (tens[x // 10] + (" " + ones[x % 10] if x % 10 else "")).strip()
        return (ones[x // 100] + " Hundred" + (" " + _under_thousand(x % 100) if x % 100 else "")).strip()

    rupees = int(n)
    paisa = int(round((n - rupees) * 100))
    if paisa == 100:
        rupees += 1
        paisa = 0

    if rupees == 0:
        words = "Zero"
    else:
        parts = []
        crore = rupees // 10000000
        lakh = (rupees // 100000) % 100
        thousand = (rupees // 1000) % 100
        rest = rupees % 1000
        if crore:
            parts.append(_under_thousand(crore) + " Crore")
        if lakh:
            parts.append(_under_thousand(lakh) + " Lakh")
        if thousand:
            parts.append(_under_thousand(thousand) + " Thousand")
        if rest:
            parts.append(_under_thousand(rest))
        words = " ".join(parts)

    out = f"Rupees {words} Only"
    if paisa:
        out = f"Rupees {words} and {_under_thousand(paisa)} Paisa Only"
    return out


def document_footer_html(user_id=None, *, label=None) -> str:
    """Print footer: user name only (no timestamp / company)."""
    name = resolve_preparer_name(user_id)
    if not name:
        return ""
    if label is None:
        label = "Prepared by" if user_id else "Generated by"
    return f'<div class="footer">{escape(label)}: {escape(name)}</div>'


def document_preparer_user_id(record) -> int | None:
    """User id for footer — document creator, else approver if present."""
    if not record:
        return None
    return record.get("created_by") or record.get("approved_by")


def document_poster_user_id(record) -> int | None:
    """User who posted the voucher (JV posted_by, else creator)."""
    if not record:
        return None
    return record.get("posted_by") or record.get("created_by")


def resolve_preparer_name(user_id=None) -> str:
    """Display name for Prepared By — document creator, else current logged-in user."""
    if user_id:
        try:
            for u in db.get_users():
                if u.get("id") == user_id:
                    return (u.get("full_name") or u.get("username") or "").strip()
        except Exception:
            pass
    try:
        import streamlit as st
        u = st.session_state.get("user")
        if u:
            return (u.get("full_name") or u.get("username") or "").strip()
    except Exception:
        pass
    return ""


SYSTEM_GENERATED_DISCLAIMER = (
    "This is a system-generated document. It does not require any signature or stamp."
)


def system_generated_notice_html(doc_label: str = "document", extra_line: str = "") -> str:
    """Footer notice instead of signature lines on auto-printed ERP output."""
    label = (doc_label or "document").strip().lower()
    text = f"This is a system-generated {label}. It does not require any signature or stamp."
    extra = ""
    if extra_line:
        extra = f'<p class="sig-note">{escape(extra_line)}</p>'
    return (
        f'<div class="sys-generated-notice"><p>{escape(text)}</p></div>{extra}'
    )


def cash_signatures_html(
    prepared_name: str = "",
    *,
    extra_roles: tuple[tuple[str, str], ...] = (),
) -> str:
    """Signature block for cash / bank vouchers (optional extra roles e.g. Receiver)."""
    blank = "\u00a0"
    roles: list[tuple[str, str]] = [
        ("Prepared By", prepared_name),
        ("Checked By", ""),
        ("Approved By", ""),
    ]
    roles.extend(extra_roles)
    cells = []
    for label, show_name in roles:
        nm = escape((show_name or "").strip() or blank)
        cells.append(
            f'<div class="sig-cell"><div class="sig-prepared-name">{nm}</div>'
            f'<div class="sig-line"></div><div class="sig-role">{escape(label)}</div></div>'
        )
    sig_class = "signatures cash-sig-block" + (" sig-4" if len(roles) >= 4 else "")
    return f'<div class="{sig_class}">{"".join(cells)}</div>'


def posted_by_block_html(user_id=None) -> str:
    """JV / party transfer — show who posted the entry."""
    name = resolve_preparer_name(user_id)
    if not name:
        return ""
    return f'<p class="posted-by-line"><b>Posted by:</b> {escape(name)}</p>'


def signature_block_html(
    extra_line="",
    prepared_by=None,
    *,
    doc_label: str = "document",
    style: str = PRINT_STYLE_SYSTEM,
    user_id=None,
) -> str:
    uid = user_id if user_id is not None else prepared_by
    if style == PRINT_STYLE_CASH:
        return cash_signatures_html(resolve_preparer_name(uid), extra_roles=())
    if style == PRINT_STYLE_POSTED:
        return posted_by_block_html(uid)
    return system_generated_notice_html(doc_label, extra_line)


def is_cash_ledger_title(title: str) -> bool:
    t = (title or "").strip().lower()
    return t.startswith("cash book") or t.startswith("bank book")


def _doc_header(title, doc_no, doc_date, party_label, party_name, extra_meta=None, *, party_on_new_line=False, doc_time=None):
    extra = ""
    if extra_meta:
        # Avoid duplicating Time when Date/Time already includes it
        meta_items = {
            k: v for k, v in (extra_meta or {}).items()
            if str(k).strip().lower() not in ("time", "date / time", "datetime")
        }
        if meta_items:
            extra = '<div class="summary-box">' + "".join(
                f"<div><b>{escape(k)}:</b> {escape(str(v))}</div>" for k, v in meta_items.items()
            ) + "</div>"
    dt_disp = fmt_datetime(doc_date, doc_time)
    meta_parts = [
        f"<span><b>Document No:</b> {escape(doc_no)}</span>",
        f"<span><b>Date / Time:</b> {escape(dt_disp)}</span>",
    ]
    if not party_on_new_line:
        meta_parts.append(
            f"<span><b>{escape(party_label)}:</b> {escape(party_name or '—')}</span>"
        )
    party_block = ""
    if party_on_new_line:
        party_block = (
            f'<div class="party-block">'
            f'<div class="party-label">{escape(party_label)}</div>'
            f'<div class="party-name"><b>{escape(party_name or "—")}</b></div>'
            f"</div>"
        )
    return f"""
    {company_letterhead_html()}
    <h2>{escape(title)}</h2>
    <div class="meta">{"".join(meta_parts)}</div>
    {party_block}
    {extra}
    """


_LINE_COL_WEIGHTS = {
    "item_code": 12, "product_code": 12, "code": 11,
    "item_name": 36, "product_name": 36, "product": 34,
    "quantity": 9, "qty": 9, "unit": 7,
    "net_weight": 11, "rate": 9, "discount_pct": 8, "line_discount": 10,
    "amount": 11,
}


def _line_col_widths(cols) -> list[float]:
    weights = [_LINE_COL_WEIGHTS.get(c[0], 10) for c in cols]
    total = sum(weights) or 1.0
    return [100.0 * w / total for w in weights]


_NUM_LINE_COLS = frozenset({
    "quantity", "qty", "net_weight", "rate", "amount",
    "discount_pct", "line_discount", "tax_amount",
})


def _lines_table(items, cols):
    pcts = _line_col_widths(cols)
    colgroup = "".join(f'<col style="width:{p:.1f}%">' for p in pcts)
    thead = "".join(
        f"<th class='{'num' if c[0] in _NUM_LINE_COLS else ''}'>{escape(c[1])}</th>"
        for c in cols
    )
    rows = ""
    for it in items:
        rows += "<tr>" + "".join(
            f"<td class='{'num' if c[0] in _NUM_LINE_COLS else ('wrap' if c[0] in ('item_name', 'product_name') else '')}'>"
            f"{escape(str(it.get(c[0], '') or ''))}</td>"
            for c in cols
        ) + "</tr>"
    return (
        f"<table class='data lines-table'><colgroup>{colgroup}</colgroup>"
        f"<thead><tr>{thead}</tr></thead><tbody>{rows}</tbody></table>"
    )


def _invoice_line_cols_and_format(
    items: list, *, include_weight: bool = True, hide_rates: bool = False, rate_decimals: int = 2,
) -> tuple:
    """Build print columns; include Disc % / Disc when any line has discount."""
    from product_rates_legacy import _implied_line_discount_pct

    has_wt = include_weight and any(float(it.get("net_weight") or 0) for it in items)
    # Pre-resolve disc so FMYE-style amount < qty*rate lines count
    for it in items:
        qty = float(it.get("quantity") or 0)
        rate = float(it.get("rate") or 0)
        disc_amt = float(it.get("line_discount") or 0)
        disc_pct = float(it.get("discount_pct") or 0)
        if disc_pct <= 0.0001:
            disc_pct = _implied_line_discount_pct(qty, rate, disc_amt, it.get("amount"), 0)
        it["_disc_pct_resolved"] = disc_pct
        if disc_amt <= 0.0001 and disc_pct > 0.0001 and qty * rate > 0:
            it["_disc_amt_resolved"] = round(qty * rate * disc_pct / 100.0, 2)
        else:
            it["_disc_amt_resolved"] = disc_amt

    has_disc = (not hide_rates) and any(float(it.get("_disc_pct_resolved") or 0) > 0.005 for it in items)
    cols = [("item_name", "Product"), ("quantity", "Qty")]
    if has_wt:
        cols.append(("net_weight", "Net Wt (kg)"))
    if not hide_rates:
        cols.append(("rate", "Rate"))
        if has_disc:
            cols.append(("discount_pct", "Disc %"))
            cols.append(("line_discount", "Disc"))
        cols.append(("amount", "Amount"))

    rd = max(0, int(rate_decimals or 2))
    total_wt = 0.0
    for it in items:
        qty = float(it.get("quantity") or 0)
        rate = float(it.get("rate") or 0)
        disc_pct = float(it.get("_disc_pct_resolved") or 0)
        disc_amt = float(it.get("_disc_amt_resolved") or 0)
        it["quantity"] = f"{qty:,.2f}"
        it["rate"] = f"{rate:,.{rd}f}"
        it["amount"] = f"{float(it.get('amount', 0)):,.2f}"
        nw = float(it.get("net_weight") or 0)
        it["net_weight"] = f"{nw:,.3f}"
        total_wt += nw
        if has_disc:
            it["discount_pct"] = f"{disc_pct:,.2f}" if disc_pct > 0.005 else "—"
            it["line_discount"] = f"{disc_amt:,.2f}" if disc_amt > 0.005 else "—"
    return cols, total_wt, has_disc


def _totals_block(lines):
    return '<div class="summary-box">' + "".join(f"<div>{l}</div>" for l in lines) + "</div>"


def _wrap_doc(body, title, page_mode="half", user_id=None, *, footer_label=None, skip_footer=False):
    """page_mode 'half' = A4 portrait voucher (top 50%); 'full' = A4 portrait full page (invoices)."""
    footer = "" if skip_footer else document_footer_html(user_id, label=footer_label)
    if page_mode == "full":
        css = PRINT_CSS_PORTRAIT_FULL
        inner = f'<div class="doc-wrap">{body}{footer}</div>'
    else:
        css = PRINT_CSS_PORTRAIT_HALF
        inner = f"""<div class="half-page-sheet">{body}
    {footer}</div>
    <div class="half-page-cut">— cut line — bottom half blank (50% page) —</div>
    <div class="half-page-blank no-print">Bottom half of A4 left blank</div>"""
    return f"""<!DOCTYPE html><html><head><meta charset="utf-8"><title>{escape(title)}</title>
    {css}<script>function doPrint(){{window.print();}}</script></head><body>{inner}
    <p class="no-print"><button class="print-btn" onclick="doPrint()">Print</button></p></body></html>"""


_VOUCHER_PRINT_CSS_EXTRA = """
.signatures.cash-sig-block.sig-4 { flex-wrap: nowrap; gap: 8px; }
.signatures.cash-sig-block.sig-4 .sig-cell { flex: 1 1 22%; min-width: 0; }
.signatures.cash-sig-block.sig-4 .sig-role { font-size: 10px; }
.copy-banner {
  text-align: center; font-weight: 700; font-size: 10px; letter-spacing: .08em;
  border: 1px solid #111; padding: 4px 8px; margin: 0 0 6px 0;
}
/* One A4: office copy top half, cut line, customer copy bottom half */
.voucher-dual-a4 {
  width: 100%; max-width: 210mm; margin: 0 auto;
  height: 297mm; max-height: 297mm;
  display: flex; flex-direction: column; box-sizing: border-box;
  overflow: hidden; background: #fff;
}
.voucher-dual-a4 .half-page-sheet {
  flex: 1 1 0; min-height: 0; max-height: none;
  height: auto; margin: 0; overflow: hidden;
  padding: 6px 8px; border: none;
}
.voucher-dual-a4 .half-page-sheet .header { padding-bottom: 4px; margin-bottom: 6px; }
.voucher-dual-a4 .half-page-sheet .header h1 { font-size: 15px; }
.voucher-dual-a4 .half-page-sheet h2 { font-size: 13px; margin: 4px 0; }
.voucher-dual-a4 .half-page-sheet .meta { margin: 4px 0; font-size: 10px; }
.voucher-dual-a4 .half-page-sheet .party-block .party-name { font-size: 15px; }
.voucher-dual-a4 .half-page-sheet .summary-box { padding: 6px 10px; margin: 4px 0; font-size: 10px; }
.voucher-dual-a4 .half-page-sheet .voucher-amt-box { padding: 8px; margin: 8px 0; }
.voucher-dual-a4 .half-page-sheet .voucher-amt-value { font-size: 17px; }
.voucher-amt-words { font-size: 12px; margin-top: 6px; line-height: 1.4; color: #111; }
.voucher-dual-a4 .half-page-sheet .signatures { margin-top: 10px; }
.voucher-dual-a4 .half-page-sheet .sig-line { min-height: 22px; }
.voucher-dual-a4 .half-page-cut.dual-mid-cut {
  flex: 0 0 auto; margin: 0; padding: 3px 0;
  border-top: 1px dashed #111; border-bottom: 1px dashed #111;
  text-align: center; font-size: 8px; font-weight: 600; color: #111;
  background: #fff;
}
@media print {
  body.voucher-dual-body { margin: 0; padding: 0; }
  .voucher-dual-a4 {
    height: 277mm; max-height: 277mm;
    page-break-inside: avoid; page-break-after: avoid;
  }
  .voucher-dual-a4 .half-page-sheet {
    page-break-inside: avoid; page-break-after: avoid !important;
    max-height: 136mm;
  }
  .voucher-dual-a4 .half-page-cut.dual-mid-cut { display: block !important; }
}
"""


def _receipt_voucher_dual_inner(body: str, prepared_name: str, party_name: str) -> str:
    """Office + customer copies on one A4 (inner markup only)."""
    sig_office = cash_signatures_html(
        prepared_name,
        extra_roles=(("Received By", ""),),
    )
    sig_customer = cash_signatures_html(
        prepared_name,
        extra_roles=(("Paid By", party_name or ""),),
    )
    office = (
        f'<div class="half-page-sheet">'
        f'<div class="copy-banner">OFFICE COPY</div>{body}{sig_office}</div>'
    )
    customer = (
        f'<div class="half-page-sheet">'
        f'<div class="copy-banner">CUSTOMER COPY</div>{body}{sig_customer}</div>'
    )
    return (
        f'<div class="voucher-dual-a4">{office}'
        f'<div class="half-page-cut dual-mid-cut">— — — CUT HERE — OFFICE / CUSTOMER — — —</div>'
        f"{customer}</div>"
    )


def _payment_voucher_half_inner(body: str, prepared_name: str, party_name: str) -> str:
    """Payment voucher: top half of A4 + cut line (inner markup only)."""
    sigs = cash_signatures_html(
        prepared_name,
        extra_roles=(("Receiver", party_name or ""),),
    )
    return (
        f'<div class="half-page-sheet">{body}{sigs}</div>'
        f'<div class="half-page-cut">— cut line — bottom half blank (50% page) —</div>'
        f'<div class="half-page-blank no-print">Bottom half of A4 left blank</div>'
    )


def _wrap_receipt_voucher_dual(body: str, title: str, prepared_name: str, party_name: str) -> str:
    """Receipt voucher: office copy + customer copy on one print (two half-page sets)."""
    css = PRINT_CSS_PORTRAIT_HALF.replace(
        "</style>", f"{_VOUCHER_PRINT_CSS_EXTRA}</style>",
    )
    inner = _receipt_voucher_dual_inner(body, prepared_name, party_name)
    return f"""<!DOCTYPE html><html><head><meta charset="utf-8"><title>{escape(title)}</title>
    {css}<script>function doPrint(){{window.print();}}</script></head><body class="voucher-dual-body">{inner}
    <p class="no-print"><button class="print-btn" onclick="doPrint()">Print (Office + Customer)</button></p>
    </body></html>"""


_VOUCHER_BATCH_CSS = """
.voucher-batch-page { width: 100%; max-width: 210mm; margin: 0 auto 12px auto; background: #fff; }
.voucher-batch-page + .voucher-batch-page { border-top: 1px dashed #999; padding-top: 12px; }
@media print {
  body.voucher-batch-body { margin: 0; padding: 0; }
  .voucher-batch-page {
    border: none !important; padding: 0 !important; margin: 0 !important;
    page-break-after: always; page-break-inside: avoid;
  }
  .voucher-batch-page:last-child { page-break-after: auto; }
  .voucher-batch-page .half-page-sheet {
    page-break-inside: avoid; height: 148mm !important; max-height: 148mm !important;
  }
  .voucher-batch-page .voucher-dual-a4 {
    height: 277mm; max-height: 277mm;
    page-break-inside: avoid;
  }
  .voucher-batch-page .half-page-blank { display: none !important; }
}
"""


def _finance_voucher_body(v: dict) -> tuple[str, str, str, str]:
    """Build voucher HTML body; returns (body, title, prepared_name, party_name)."""
    pt = v.get("party_type")
    side = v.get("side")
    titles = {
        ("customer", "receipt"): "Customer Receipt Voucher",
        ("supplier", "payment"): "Supplier Payment Voucher",
        ("expense", "payment"): "Expense Payment Voucher",
    }
    title = titles.get((pt, side))
    if not title:
        if side == "receipt":
            title = f"{'Cash' if v['book'] == 'cash' else 'Bank'} Receipt Voucher"
        else:
            title = f"{'Cash' if v['book'] == 'cash' else 'Bank'} Payment Voucher"
    extra = {
        "Reference": v.get("reference_no") or "—",
        "Payment Mode": v.get("payment_mode") or "—",
    }
    if v.get("bank_account"):
        key = "Cash Account" if v.get("book") == "cash" else "Bank Account"
        extra[key] = v["bank_account"]
    if v.get("party_code"):
        extra["Party Code"] = v["party_code"]
    prep = document_preparer_user_id(v)
    prepared_name = resolve_preparer_name(prep) if prep else ""
    if prepared_name:
        extra["Prepared By"] = prepared_name

    party_name = (v.get("party_name") or "").strip()
    party_label = v.get("party_kind") or ("Received From" if side == "receipt" else "Paid To")
    # Prefer code + name for the prominent party block
    party_display = party_name
    if v.get("party_code") and party_name and str(v.get("party_code")) not in party_name:
        party_display = f"{v['party_code']} - {party_name}"
    if not party_display:
        party_display = "—"

    body = _doc_header(
        title, v.get("document_no", ""), v.get("txn_date"), party_label,
        party_display, extra,
        party_on_new_line=True,
        doc_time=v.get("created_at"),
    )
    narr = (v.get("description") or "").strip()
    if narr:
        body += f"<p><b>Narration:</b> {escape(narr)}</p>"
    amt_label = "Amount Received" if side == "receipt" else "Amount Paid"
    body += _voucher_amount_box(amt_label, v.get("amount", 0), v.get("payment_mode", ""))
    if v.get("party_balance") is not None and pt in ("customer", "supplier"):
        body += _totals_block([
            f"<b>Party ledger balance (after posting):</b> Rs. {float(v.get('party_balance', 0)):,.2f}",
        ])
    return body, title, prepared_name, party_name


def _voucher_amount_box(label, amount, mode=""):
    amt = float(amount or 0)
    mode_txt = f"<div><b>Mode:</b> {escape(mode)}</div>" if mode else ""
    words = amount_in_words(amt)
    return f"""
    <div class="voucher-amt-box">
        <div class="voucher-amt-label">{escape(label)}</div>
        <div class="voucher-amt-value">Rs. {amt:,.2f}</div>
        <div class="voucher-amt-words"><b>Amount in Words:</b> {escape(words)}</div>
        {mode_txt}
    </div>
    """


def _weight_block(inv):
    inv_wt = float(inv.get("invoice_weight_kg") or inv.get("total_net_weight") or 0)
    phys = inv.get("physical_weight_kg")
    var = inv.get("weight_variance_kg")
    var_pct = inv.get("weight_variance_pct")
    if phys is not None and inv_wt:
        var = round(float(phys) - inv_wt, 3)
        base = inv_wt if inv_wt > 0 else float(phys or 1)
        var_pct = round(abs(var) / base * 100, 2)
    lines = []
    if inv_wt:
        lines.append(f"<b>Invoice Total Weight:</b> {inv_wt:,.3f} kg")
    if inv.get("weight_slip_no"):
        lines.append(f"<b>Weight Slip:</b> {escape(inv['weight_slip_no'])}")
    if phys is not None:
        lines.append(f"<b>Physical Weight (Scale):</b> {phys:,.3f} kg")
    if var is not None:
        cls = "variance-ok" if abs(var) < 0.5 else ("variance-warn" if abs(var) < 5 else "variance-bad")
        pct_txt = f" ({var_pct:.2f}%)" if var_pct is not None else ""
        lines.append(f"<b>Variance:</b> <span class='{cls}'>{var:+,.3f} kg{pct_txt}</span>")
    if inv.get("weight_match_status"):
        lines.append(f"<b>Match Status:</b> {escape(str(inv['weight_match_status']).replace('_', ' ').title())}")
    if inv.get("override_reason"):
        lines.append(f"<b>Variance Override:</b> {escape(inv['override_reason'])}")
    return _totals_block(lines) if lines else ""


def sales_invoice_html(sale_id, tax_invoice=False):
    inv = db.get_sale(sale_id)
    if not inv:
        return ""
    title = "Sales Tax Invoice" if tax_invoice else "Sales Invoice"
    meta = {
        "Status": inv.get("status", "—").replace("_", " ").title(),
        "Gate Pass": inv.get("gate_pass_no") or "—",
    }
    if not inv.get("gate_pass_no") and inv.get("gate_pass_id"):
        gps = db.get_gate_passes(sales_invoice_id=sale_id)
        if gps:
            inv["gate_pass_no"] = gps[0].get("document_no")
            meta["Gate Pass"] = inv["gate_pass_no"]
    body = _doc_header(
        title, inv["invoice_no"], inv["sale_date"], "Customer", inv.get("customer_name"),
        meta,
        party_on_new_line=True,
        doc_time=inv.get("created_at") or inv.get("approved_at"),
    )
    items = inv.get("items") or []
    cols, _total_wt, has_disc = _invoice_line_cols_and_format(items, include_weight=False)
    body += _lines_table(items, cols)
    prev_bal = db.get_customer_balance_before_ref(
        inv["customer_id"], inv["invoice_no"], inv.get("sale_date"),
    )
    total = float(inv.get("total", 0))
    paid = float(inv.get("paid_amount") or 0)
    balance_due = prev_bal + total - paid
    disc_label = "Item Discount" if has_disc else "Discount"
    body += _totals_block([
        f"<b>Subtotal:</b> Rs. {float(inv.get('subtotal', 0)):,.2f}",
        f"<b>{disc_label}:</b> Rs. {float(inv.get('discount', 0)):,.2f}",
        f"<b>Tax:</b> Rs. {float(inv.get('tax', 0)):,.2f}",
        f"<b>Previous Balance:</b> Rs. {prev_bal:,.2f}",
        f"<b>Net Total:</b> Rs. {total:,.2f}",
        f"<b>Paid:</b> Rs. {paid:,.2f}",
        f"<b>Balance Due:</b> Rs. {balance_due:,.2f}",
    ])
    body += signature_block_html(doc_label="invoice")
    return _wrap_doc(body, f"{title} {inv['invoice_no']}", page_mode="full", user_id=document_preparer_user_id(inv))


def sales_invoice_pdf_bytes(sale_id, *, tax_invoice: bool = False, include_company: bool = True) -> bytes:
    """Proper Sales Invoice PDF (not HTML scrape) for Download PDF."""
    from fpdf import FPDF

    inv = db.get_sale(sale_id)
    if not inv:
        raise ValueError("Sales invoice not found.")

    gp_no = inv.get("gate_pass_no") or ""
    if not gp_no and inv.get("gate_pass_id"):
        gps = db.get_gate_passes(sales_invoice_id=sale_id)
        if gps:
            gp_no = gps[0].get("document_no") or ""

    prev_bal = db.get_customer_balance_before_ref(
        inv["customer_id"], inv["invoice_no"], inv.get("sale_date"),
    )
    total = float(inv.get("total") or 0)
    paid = float(inv.get("paid_amount") or 0)
    disc = float(inv.get("discount") or 0)
    tax = float(inv.get("tax") or 0)
    balance_due = prev_bal + total - paid
    status = str(inv.get("status") or "—").replace("_", " ").title()
    title = "SALES TAX INVOICE" if tax_invoice else "SALES INVOICE"
    items = list(inv.get("items") or [])
    has_disc = any(float(it.get("discount_pct") or it.get("line_discount") or 0) > 0.005 for it in items)

    pdf = FPDF(format="A4")
    pdf.set_auto_page_break(auto=True, margin=14)
    pdf.add_page()
    pdf.set_margins(14, 14, 14)

    if include_company:
        co = get_company_info()
        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 8, _pdf_latin1(co.get("name") or "IFS Chemicals"), new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", size=8)
        bits = [co.get("address"), co.get("phone"), co.get("email")]
        line = " | ".join(b for b in bits if b)
        if line:
            pdf.cell(0, 5, _pdf_latin1(line), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 7, title, new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", size=10)
    pdf.cell(0, 6, _pdf_latin1(f"No: {inv.get('invoice_no') or ''}"), new_x="LMARGIN", new_y="NEXT")
    pdf.cell(
        0, 6,
        _pdf_latin1(
            f"Date: {fmt_datetime(inv.get('sale_date'), inv.get('created_at') or inv.get('approved_at'))}"
            f"  |  Status: {status}"
        ),
        new_x="LMARGIN", new_y="NEXT",
    )
    pdf.cell(
        0, 6,
        _pdf_latin1(f"Customer: {inv.get('customer_name') or '—'}"),
        new_x="LMARGIN", new_y="NEXT",
    )
    if gp_no:
        pdf.cell(0, 6, _pdf_latin1(f"Gate Pass: {gp_no}"), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    headers = [("Product", 78), ("Qty", 22), ("Rate", 28), ("Amount", 32)]
    if has_disc:
        headers = [("Product", 58), ("Qty", 18), ("Rate", 24), ("Disc %", 18), ("Amount", 32)]
    pdf.set_font("Helvetica", "B", 8)
    for label, w in headers:
        pdf.cell(w, 6, label, border=1)
    pdf.ln()
    pdf.set_font("Helvetica", size=8)

    for src in items:
        name = src.get("item_name") or src.get("product_name") or ""
        qty = float(src.get("quantity") or 0)
        rate = float(src.get("rate") or 0)
        amt = float(src.get("amount") or 0)
        prod = _pdf_latin1(name)[:48]
        row = [
            (prod, headers[0][1]),
            (f"{qty:,.2f}", headers[1][1]),
            (f"{rate:,.2f}", headers[2][1]),
        ]
        if has_disc:
            dp = float(src.get("discount_pct") or 0)
            row.append((f"{dp:,.2f}" if dp > 0.005 else "-", headers[3][1]))
            row.append((f"{amt:,.2f}", headers[4][1]))
        else:
            row.append((f"{amt:,.2f}", headers[3][1]))
        for text, w in row:
            pdf.cell(w, 6, text, border=1)
        pdf.ln()

    pdf.ln(4)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 6, _pdf_latin1(f"Subtotal: Rs. {float(inv.get('subtotal') or 0):,.2f}"), new_x="LMARGIN", new_y="NEXT")
    if disc > 0.005 or has_disc:
        pdf.cell(0, 6, _pdf_latin1(f"{'Item Discount' if has_disc else 'Discount'}: Rs. {disc:,.2f}"), new_x="LMARGIN", new_y="NEXT")
    if tax > 0.005:
        pdf.cell(0, 6, _pdf_latin1(f"Tax: Rs. {tax:,.2f}"), new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, _pdf_latin1(f"Previous Balance: Rs. {prev_bal:,.2f}"), new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, _pdf_latin1(f"Net Total: Rs. {total:,.2f}"), new_x="LMARGIN", new_y="NEXT")
    if paid > 0.005:
        pdf.cell(0, 6, _pdf_latin1(f"Paid: Rs. {paid:,.2f}"), new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, _pdf_latin1(f"Balance Due: Rs. {balance_due:,.2f}"), new_x="LMARGIN", new_y="NEXT")
    if inv.get("notes"):
        pdf.set_font("Helvetica", size=9)
        pdf.multi_cell(0, 5, _pdf_latin1(f"Notes: {inv['notes']}"))
    pdf.set_font("Helvetica", size=8)
    pdf.ln(2)
    pdf.cell(0, 5, "This is a system-generated invoice.", new_x="LMARGIN", new_y="NEXT")
    prep = resolve_preparer_name(document_preparer_user_id(inv))
    if prep:
        pdf.cell(0, 5, _pdf_latin1(f"Prepared by: {prep}"), new_x="LMARGIN", new_y="NEXT")

    return bytes(pdf.output())


def purchase_invoice_html(purchase_id):
    inv = db.get_purchase(purchase_id)
    if not inv:
        return ""
    with db.get_connection() as conn:
        from db_invoice_workflow import refresh_invoice_weight_match
        refresh_invoice_weight_match(conn, purchase_id, "purchase")
        inv.update(db.get_invoice_weight_info(purchase_id, "purchase"))
    body = _doc_header(
        "Purchase Invoice", inv["invoice_no"], inv["purchase_date"], "Supplier", inv.get("supplier_name"),
        party_on_new_line=True,
        doc_time=inv.get("created_at") or inv.get("approved_at"),
    )
    items = inv.get("items") or []
    cols, total_wt, has_disc = _invoice_line_cols_and_format(items, rate_decimals=4)
    body += _lines_table(items, cols)
    prev_bal = db.get_supplier_balance_before_ref(
        inv["supplier_id"], inv["invoice_no"], inv.get("purchase_date"),
    )
    total = float(inv.get("total", 0))
    paid = float(inv.get("paid_amount") or 0)
    balance_due = prev_bal + total - paid
    disc_label = "Item Discount" if has_disc else "Discount"
    body += _totals_block([
        f"<b>Subtotal:</b> Rs. {float(inv.get('subtotal', 0)):,.2f}",
        f"<b>{disc_label}:</b> Rs. {float(inv.get('discount', 0)):,.2f}",
        f"<b>Tax:</b> Rs. {float(inv.get('tax', 0)):,.2f}",
        f"<b>Previous Balance:</b> Rs. {prev_bal:,.2f}",
        f"<b>Net Total:</b> Rs. {total:,.2f}",
        f"<b>Paid:</b> Rs. {paid:,.2f}",
        f"<b>Balance Due:</b> Rs. {balance_due:,.2f}",
        f"<b>Total Item Weight:</b> {total_wt:,.3f} kg",
    ])
    body += _weight_block(inv)
    body += signature_block_html(doc_label="invoice")
    return _wrap_doc(body, f"Purchase {inv['invoice_no']}", page_mode="full", user_id=document_preparer_user_id(inv))


def sale_return_html(return_id):
    ret = db.get_sale_return(return_id)
    if not ret:
        return ""
    meta = {
        "Customer Code": ret.get("customer_code") or "—",
        "Against Invoice": ret.get("invoice_no") or "—",
    }
    if ret.get("notes"):
        meta["Notes"] = ret["notes"]
    body = _doc_header(
        "Sale Return", ret["return_no"], ret["return_date"],
        "Customer", ret.get("customer_name"),
        meta,
        party_on_new_line=True,
        doc_time=ret.get("created_at") or ret.get("modified_at"),
    )
    items = ret.get("items") or []
    cols, _total_wt, _has_disc = _invoice_line_cols_and_format(items, include_weight=False)
    body += _lines_table(items, cols)
    body += _totals_block([
        f"<b>Subtotal:</b> Rs. {float(ret.get('subtotal', 0)):,.2f}",
        f"<b>Net Return:</b> Rs. {float(ret.get('total', 0)):,.2f}",
    ])
    body += signature_block_html(doc_label="sale return")
    return _wrap_doc(
        body, f"Sale Return {ret['return_no']}",
        page_mode="full", user_id=document_preparer_user_id(ret),
    )


def purchase_return_html(return_id):
    ret = db.get_purchase_return(return_id)
    if not ret:
        return ""
    meta = {
        "Supplier Code": ret.get("supplier_code") or "—",
        "Against Invoice": ret.get("invoice_no") or "—",
    }
    if ret.get("notes"):
        meta["Notes"] = ret["notes"]
    body = _doc_header(
        "Purchase Return", ret["return_no"], ret["return_date"],
        "Supplier", ret.get("supplier_name"),
        meta,
        party_on_new_line=True,
        doc_time=ret.get("created_at") or ret.get("modified_at"),
    )
    items = ret.get("items") or []
    cols, total_wt, has_disc = _invoice_line_cols_and_format(items, rate_decimals=4)
    body += _lines_table(items, cols)
    body += _totals_block([
        f"<b>Subtotal:</b> Rs. {float(ret.get('subtotal', 0)):,.2f}",
        f"<b>Net Return:</b> Rs. {float(ret.get('total', 0)):,.2f}",
        f"<b>Total Item Weight:</b> {total_wt:,.3f} kg",
    ])
    body += signature_block_html(doc_label="purchase return")
    return _wrap_doc(
        body, f"Purchase Return {ret['return_no']}",
        page_mode="full", user_id=document_preparer_user_id(ret),
    )


def sales_order_html(order_id, *, hide_rates: bool = False):
    inv = db.get_sales_order(order_id)
    if not inv:
        return ""
    extra = {
        "Status": _so_status_display(inv.get("status")),
        "Customer Code": inv.get("customer_code") or "—",
    }
    if inv.get("delivery_date"):
        extra["Delivery Date"] = inv["delivery_date"]
    town = (inv.get("dispatch_town") or "").strip()
    if not town:
        try:
            from erp_core.dispatch_planning import resolve_dispatch_to
            city = ""
            try:
                from database import get_connection
                with get_connection() as conn:
                    crow = conn.execute(
                        "SELECT city FROM customers WHERE id=?", (inv.get("customer_id"),)
                    ).fetchone()
                    if crow:
                        city = crow[0] or ""
            except Exception:
                city = ""
            dest = resolve_dispatch_to(inv.get("notes"), city)
            if dest and dest != "-":
                town = dest
        except Exception:
            pass
    if town:
        extra["Delivery Stop"] = town
    body = _doc_header(
        "Sales Order", inv["document_no"], inv["order_date"],
        "Customer", inv.get("customer_name"),
        extra,
        party_on_new_line=True,
        doc_time=inv.get("created_at"),
    )
    items = []
    for src in inv.get("items") or []:
        it = dict(src)
        name = it.get("product_name") or it.get("item_name") or ""
        code = (it.get("product_code") or "").strip()
        it["item_name"] = f"{code} — {name}" if code else name
        # Estimated net weight from standard weight × qty when no explicit net_weight
        if not float(it.get("net_weight") or 0):
            sw = float(it.get("standard_weight") or 0)
            qty = float(it.get("quantity") or 0)
            if sw > 0 and qty > 0:
                it["net_weight"] = round(sw * qty, 3)
        items.append(it)
    total_qty = sum(float(it.get("quantity") or 0) for it in items)
    cols, total_wt, has_disc = _invoice_line_cols_and_format(items, hide_rates=hide_rates)
    # Prefer unit column when present and no weight column crowding
    if any((it.get("unit") or "").strip() for it in items):
        # Insert Unit after Qty if not already showing weight-heavy layout
        names = [c[0] for c in cols]
        if "unit" not in names:
            qty_i = names.index("quantity") + 1 if "quantity" in names else 1
            cols = cols[:qty_i] + [("unit", "Unit")] + cols[qty_i:]
            for it in items:
                it["unit"] = (it.get("unit") or "").strip()
    body += _lines_table(items, cols)
    totals = []
    if not hide_rates:
        totals.append(f"<b>Subtotal:</b> Rs. {float(inv.get('subtotal', 0)):,.2f}")
        disc = float(inv.get("discount") or 0)
        tax = float(inv.get("tax") or 0)
        if disc > 0.005 or has_disc:
            totals.append(f"<b>{'Item Discount' if has_disc else 'Discount'}:</b> Rs. {disc:,.2f}")
        if tax > 0.005:
            totals.append(f"<b>Tax:</b> Rs. {tax:,.2f}")
        totals.append(f"<b>Total:</b> Rs. {float(inv.get('total', 0)):,.2f}")
    if total_qty > 0.0005:
        totals.append(f"<b>Total Quantity:</b> {total_qty:,.2f}")
        # Break down by unit when more than one unit is used
        by_unit: dict[str, float] = {}
        for it in inv.get("items") or []:
            u = (it.get("unit") or "").strip() or "—"
            by_unit[u] = by_unit.get(u, 0.0) + float(it.get("quantity") or 0)
        if len(by_unit) > 1:
            parts = [f"{escape(u)}: {q:,.2f}" for u, q in sorted(by_unit.items(), key=lambda x: x[0])]
            totals.append(f"<b>Qty by Unit:</b> {' · '.join(parts)}")
    if total_wt > 0.0005:
        totals.append(f"<b>Total Item Weight:</b> {total_wt:,.3f} kg")
    if inv.get("notes"):
        totals.append(f"<b>Notes:</b> {escape(str(inv['notes']))}")
    if totals:
        body += _totals_block(totals)
    body += signature_block_html(doc_label="sales order")
    return _wrap_doc(
        body, inv["document_no"], page_mode="full",
        user_id=document_preparer_user_id(inv),
    )


def _pdf_latin1(text) -> str:
    """FPDF core fonts need Latin-1; replace common Unicode punctuation."""
    if text is None:
        return ""
    s = str(text)
    for a, b in (
        ("\u2014", "-"), ("\u2013", "-"), ("\u2018", "'"), ("\u2019", "'"),
        ("\u201c", '"'), ("\u201d", '"'), ("\u00a0", " "), ("\u2022", "*"),
        ("Rs.", "Rs."), ("—", "-"), ("–", "-"),
    ):
        s = s.replace(a, b)
    return s.encode("latin-1", "replace").decode("latin-1")


def sales_order_pdf_bytes(order_id, *, hide_rates: bool = False, include_company: bool = True) -> bytes:
    """Proper Sales Order PDF (not HTML scrape) for Download PDF."""
    from fpdf import FPDF

    inv = db.get_sales_order(order_id)
    if not inv:
        raise ValueError("Sales order not found.")

    town = (inv.get("dispatch_town") or "").strip()
    if not town:
        try:
            from erp_core.dispatch_planning import resolve_dispatch_to
            from database import get_connection
            city = ""
            with get_connection() as conn:
                crow = conn.execute(
                    "SELECT city FROM customers WHERE id=?", (inv.get("customer_id"),)
                ).fetchone()
                if crow:
                    city = crow[0] or ""
            dest = resolve_dispatch_to(inv.get("notes"), city)
            if dest and dest != "-":
                town = dest
        except Exception:
            pass

    pdf = FPDF(format="A4")
    pdf.set_auto_page_break(auto=True, margin=14)
    pdf.add_page()
    pdf.set_margins(14, 14, 14)

    if include_company:
        co = get_company_info()
        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 8, _pdf_latin1(co.get("name") or "IFS Chemicals"), new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", size=8)
        bits = [co.get("address"), co.get("phone"), co.get("email")]
        line = " | ".join(b for b in bits if b)
        if line:
            pdf.cell(0, 5, _pdf_latin1(line), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 7, "SALES ORDER", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", size=10)
    pdf.cell(0, 6, _pdf_latin1(f"No: {inv.get('document_no') or ''}"), new_x="LMARGIN", new_y="NEXT")
    pdf.cell(
        0, 6,
        _pdf_latin1(
            f"Date: {str(inv.get('order_date') or '')[:10]}  |  "
            f"Status: {_so_status_display(inv.get('status'))}"
        ),
        new_x="LMARGIN", new_y="NEXT",
    )
    pdf.cell(
        0, 6,
        _pdf_latin1(
            f"Customer: {inv.get('customer_code') or ''} — {inv.get('customer_name') or ''}"
        ),
        new_x="LMARGIN", new_y="NEXT",
    )
    if inv.get("delivery_date"):
        pdf.cell(0, 6, _pdf_latin1(f"Delivery: {inv['delivery_date']}"), new_x="LMARGIN", new_y="NEXT")
    if town:
        pdf.cell(0, 6, _pdf_latin1(f"Delivery Stop: {town}"), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    # Table header
    if hide_rates:
        headers = [("Product", 95), ("Qty", 25), ("Unit", 20), ("Net Wt", 40)]
    else:
        headers = [("Product", 70), ("Qty", 22), ("Unit", 18), ("Net Wt", 28), ("Rate", 25), ("Amount", 27)]
    pdf.set_font("Helvetica", "B", 8)
    for label, w in headers:
        pdf.cell(w, 6, label, border=1)
    pdf.ln()
    pdf.set_font("Helvetica", size=8)

    total_wt = 0.0
    total_qty = 0.0
    by_unit: dict[str, float] = {}
    for src in inv.get("items") or []:
        name = src.get("product_name") or src.get("item_name") or ""
        code = (src.get("product_code") or "").strip()
        label = f"{code} - {name}" if code else name
        qty = float(src.get("quantity") or 0)
        unit = (src.get("unit") or "").strip()
        nw = float(src.get("net_weight") or 0)
        if nw <= 0:
            sw = float(src.get("standard_weight") or 0)
            if sw > 0 and qty > 0:
                nw = round(sw * qty, 3)
        total_wt += nw
        total_qty += qty
        u_key = unit or "—"
        by_unit[u_key] = by_unit.get(u_key, 0.0) + qty
        rate = float(src.get("rate") or 0)
        amt = float(src.get("amount") or qty * rate)
        # Truncate product name to fit
        prod = _pdf_latin1(label)[:42]
        row = [
            (prod, headers[0][1]),
            (f"{qty:,.2f}", headers[1][1]),
            (_pdf_latin1(unit)[:8], headers[2][1]),
            (f"{nw:,.3f}", headers[3][1]),
        ]
        if not hide_rates:
            row.append((f"{rate:,.2f}", headers[4][1]))
            row.append((f"{amt:,.2f}", headers[5][1]))
        for text, w in row:
            pdf.cell(w, 6, text, border=1)
        pdf.ln()

    pdf.ln(4)
    pdf.set_font("Helvetica", "B", 10)
    if not hide_rates:
        pdf.cell(0, 6, _pdf_latin1(f"Total: Rs. {float(inv.get('total') or 0):,.2f}"), new_x="LMARGIN", new_y="NEXT")
    if total_qty > 0.0005:
        pdf.cell(0, 6, _pdf_latin1(f"Total Quantity: {total_qty:,.2f}"), new_x="LMARGIN", new_y="NEXT")
        if len(by_unit) > 1:
            parts = [f"{u}: {q:,.2f}" for u, q in sorted(by_unit.items(), key=lambda x: x[0])]
            pdf.set_font("Helvetica", size=9)
            pdf.cell(0, 5, _pdf_latin1(f"Qty by Unit: {' | '.join(parts)}"), new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "B", 10)
    if total_wt > 0.0005:
        pdf.cell(0, 6, _pdf_latin1(f"Total Item Weight: {total_wt:,.3f} kg"), new_x="LMARGIN", new_y="NEXT")
    if inv.get("notes"):
        pdf.set_font("Helvetica", size=9)
        pdf.multi_cell(0, 5, _pdf_latin1(f"Notes: {inv['notes']}"))
    prep = resolve_preparer_name(document_preparer_user_id(inv))
    if prep:
        pdf.set_font("Helvetica", size=8)
        pdf.ln(2)
        pdf.cell(0, 5, _pdf_latin1(f"Prepared by: {prep}"), new_x="LMARGIN", new_y="NEXT")

    return bytes(pdf.output())


def _scraped_html_pdf_bytes(html: str, title: str, *, include_company: bool = True) -> bytes:
    """Fallback PDF from HTML text (sanitized for FPDF Latin-1)."""
    from fpdf import FPDF
    import re

    pdf = FPDF(format="A4")
    pdf.set_auto_page_break(auto=True, margin=12)
    pdf.add_page()
    pdf.set_margins(12, 12, 12)
    usable = pdf.w - pdf.l_margin - pdf.r_margin
    if include_company:
        co = get_company_info()
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(usable, 7, _pdf_latin1(co.get("name") or ""), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(usable, 6, _pdf_latin1(title), new_x="LMARGIN", new_y="NEXT")
    prep = resolve_preparer_name()
    if prep:
        pdf.set_font("Helvetica", size=8)
        pdf.cell(usable, 5, _pdf_latin1(f"Generated by: {prep}"), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)
    pdf.set_font("Helvetica", size=8)
    text = html or ""
    text = re.sub(r"<style[\s\S]*?</style>", " ", text, flags=re.I)
    text = re.sub(r"<script[\s\S]*?</script>", " ", text, flags=re.I)
    text = re.sub(r"@page\s*\{[\s\S]*?\}", " ", text, flags=re.I)
    text = re.sub(r"<br\s*/?>", "\n", text, flags=re.I)
    text = re.sub(r"</tr>", "\n", text, flags=re.I)
    text = re.sub(r"<[^>]+>", " ", text)
    text = re.sub(r"[ \t]+", " ", text)
    for raw in text.split("\n"):
        clean = _pdf_latin1(raw.strip())
        if len(clean) < 2:
            continue
        # Chunk long lines so multi_cell never overflows
        while clean:
            chunk, clean = clean[:180], clean[180:]
            try:
                pdf.multi_cell(usable, 4, chunk)
            except Exception:
                pdf.cell(usable, 4, chunk[:90], new_x="LMARGIN", new_y="NEXT")
    return bytes(pdf.output())


def purchase_order_html(po_id):
    inv = db.get_purchase_order(po_id)
    if not inv:
        return ""
    extra = {
        "Status": str(inv.get("status") or "—").replace("_", " ").title(),
        "Supplier Code": inv.get("supplier_code") or "—",
    }
    if inv.get("delivery_date"):
        extra["Delivery Date"] = inv["delivery_date"]
    body = _doc_header(
        "Purchase Order", inv["document_no"], inv["order_date"],
        "Supplier", inv.get("supplier_name"),
        extra,
        party_on_new_line=True,
        doc_time=inv.get("created_at"),
    )
    items = []
    for src in inv.get("items") or []:
        it = dict(src)
        name = it.get("product_name") or it.get("item_name") or ""
        code = (it.get("product_code") or "").strip()
        it["item_name"] = f"{code} — {name}" if code else name
        if not float(it.get("net_weight") or 0):
            sw = float(it.get("standard_weight") or 0)
            qty = float(it.get("quantity") or 0)
            if sw > 0 and qty > 0:
                it["net_weight"] = round(sw * qty, 3)
        items.append(it)
    cols, total_wt, has_disc = _invoice_line_cols_and_format(items, rate_decimals=4)
    if any((it.get("unit") or "").strip() for it in items):
        names = [c[0] for c in cols]
        if "unit" not in names:
            qty_i = names.index("quantity") + 1 if "quantity" in names else 1
            cols = cols[:qty_i] + [("unit", "Unit")] + cols[qty_i:]
            for it in items:
                it["unit"] = (it.get("unit") or "").strip()
    body += _lines_table(items, cols)
    totals = [
        f"<b>Subtotal:</b> Rs. {float(inv.get('subtotal', 0)):,.2f}",
    ]
    disc = float(inv.get("discount") or 0)
    tax = float(inv.get("tax") or 0)
    if disc > 0.005 or has_disc:
        totals.append(f"<b>{'Item Discount' if has_disc else 'Discount'}:</b> Rs. {disc:,.2f}")
    if tax > 0.005:
        totals.append(f"<b>Tax:</b> Rs. {tax:,.2f}")
    totals.append(f"<b>Total:</b> Rs. {float(inv.get('total', 0)):,.2f}")
    if total_wt > 0.0005:
        totals.append(f"<b>Total Item Weight:</b> {total_wt:,.3f} kg")
    if inv.get("notes"):
        totals.append(f"<b>Notes:</b> {escape(str(inv['notes']))}")
    body += _totals_block(totals)
    body += signature_block_html(doc_label="purchase order")
    return _wrap_doc(
        body, inv["document_no"], page_mode="full",
        user_id=document_preparer_user_id(inv),
    )


def delivery_note_html(dn_id):
    rows = [r for r in db.get_delivery_notes() if r["id"] == dn_id]
    if not rows:
        return ""
    d = rows[0]
    body = _doc_header(
        "Delivery Note", d["document_no"], d["dn_date"], "Customer", d.get("customer_name"),
        {"Driver": d.get("driver_name"), "Vehicle ID": d.get("vehicle_id")},
        doc_time=d.get("created_at"),
    )
    body += _totals_block([f"<b>Total Value:</b> Rs. {float(d.get('total', 0)):,.2f}"])
    body += signature_block_html(doc_label="delivery note")
    return _wrap_doc(body, d["document_no"], user_id=document_preparer_user_id(d))


def grn_html(grn_id):
    rows = [r for r in db.get_grns() if r["id"] == grn_id]
    if not rows:
        return ""
    g = rows[0]
    body = _doc_header(
        "Goods Receipt Note", g["document_no"], g["grn_date"], "Supplier", g.get("supplier_name"),
        doc_time=g.get("created_at"),
    )
    body += _totals_block([
        f"<b>Subtotal:</b> Rs. {float(g.get('subtotal', 0)):,.2f}",
        f"<b>Tax:</b> Rs. {float(g.get('tax_total', 0)):,.2f}",
        f"<b>Total:</b> Rs. {float(g.get('total', 0)):,.2f}",
    ])
    body += signature_block_html(doc_label="GRN")
    return _wrap_doc(body, g["document_no"], user_id=document_preparer_user_id(g))


def journal_voucher_html(vid):
    jv = db.get_journal_voucher(vid)
    if not jv:
        return ""
    poster = document_poster_user_id(jv)
    meta = {}
    if poster:
        pname = resolve_preparer_name(poster)
        if pname:
            meta["Posted By"] = pname
    body = _doc_header(
        "Journal Voucher", jv["document_no"], jv["voucher_date"],
        "Description", jv.get("description", ""), meta or None,
        doc_time=jv.get("posted_at") or jv.get("created_at"),
    )
    lines = jv.get("lines") or []
    hdr_desc = (jv.get("description") or "").strip()
    for ln in lines:
        ln["account"] = f"{ln.get('account_code','')} - {ln.get('account_name','')}"
        # Line narration often blank in UI — show voucher description on print
        narr = (ln.get("description") or ln.get("narration") or "").strip() or hdr_desc
        ln["description"] = narr or "—"
    body += _lines_table(lines, [
        ("account", "Account"), ("description", "Narration"), ("debit", "Debit"), ("credit", "Credit"),
    ])
    body += _totals_block([
        f"<b>Total Debit:</b> Rs. {float(jv.get('total_debit', 0)):,.2f}",
        f"<b>Total Credit:</b> Rs. {float(jv.get('total_credit', 0)):,.2f}",
    ])
    body += signature_block_html(doc_label="journal voucher", style=PRINT_STYLE_POSTED, user_id=poster)
    return _wrap_doc(
        body, jv["document_no"], user_id=poster, footer_label="Posted by",
    )


def job_card_html(job_id):
    from db_job_cards import get_job_card, JOB_TYPES, get_material_lines

    jc = get_job_card(job_id)
    if not jc:
        return ""
    title = f"Production Job Card — {JOB_TYPES.get(jc['job_type'], jc['job_type'])}"
    extra = {
        "Produced Item": jc.get("finished_product_name") or "—",
        "Production Qty": f"{float(jc.get('finished_qty') or 0):,.2f}",
        "Status": (jc.get("status") or "draft").title(),
    }
    if jc.get("job_name"):
        extra["Job Name"] = jc["job_name"]
    body = _doc_header(
        title, jc["document_no"], jc["job_date"], "Type", JOB_TYPES.get(jc["job_type"], jc["job_type"]), extra,
        doc_time=jc.get("created_at"),
    )

    lines = get_material_lines(jc)
    if lines:
        body += "<h3>Materials consumed</h3>"
        for ln in lines:
            ln["product_code"] = ln.get("product_code") or "—"
            ln["product_name"] = ln.get("product_name") or "—"
            ln["quantity"] = f"{float(ln.get('quantity') or 0):,.2f}"
            ln["rate"] = f"{float(ln.get('rate') or 0):,.2f}"
            ln["amount"] = f"{float(ln.get('amount') or 0):,.2f}"
        body += _lines_table(lines, [
            ("product_code", "Code"), ("product_name", "Raw Material"),
            ("quantity", "Qty"), ("rate", "Rate"), ("amount", "Amount"),
        ])

    body += _totals_block([
        f"<b>Total material cost:</b> Rs. {float(jc.get('total_material_cost') or 0):,.2f}",
        f"<b>Produced qty (stock in):</b> {float(jc.get('finished_qty') or 0):,.2f}",
        f"<b>Cost per unit:</b> Rs. {float(jc.get('cost_per_unit') or 0):,.4f}",
    ])
    if jc.get("remarks"):
        body += _totals_block([f"<b>Remarks:</b> {escape(jc.get('remarks') or '')}"])
    body += signature_block_html(doc_label="job card")
    return _wrap_doc(body, jc["document_no"], page_mode="full", user_id=document_preparer_user_id(jc))


def _gate_pass_remarks_text(g: dict) -> str:
    """Combined remarks for print — gate pass + linked invoice notes."""
    parts = []
    for key in ("remarks", "purchase_notes", "sales_notes", "dispatch_remarks"):
        val = (g.get(key) or "").strip()
        if val and val not in parts:
            parts.append(val)
    return " | ".join(parts)


def _gate_pass_invoice_amount(g: dict) -> float:
    """Invoice net amount linked to this gate pass (purchase preferred, then sales)."""
    for key in ("purchase_invoice_total", "invoice_total"):
        try:
            amt = float(g.get(key) or 0)
        except (TypeError, ValueError):
            amt = 0.0
        if amt:
            return amt
    return 0.0


def _gate_pass_is_cash_sale(g: dict) -> bool:
    """True for SALE IN CASH / cash-sale outward gate passes (amounts print only then)."""
    if g.get("purchase_invoice_id") or g.get("purchase_invoice_no"):
        return False
    mode = (g.get("invoice_payment_mode") or "").strip().lower()
    if mode == "cash":
        return True
    party = (g.get("party_name") or g.get("customer_name") or "").strip().upper()
    return party in ("SALE IN CASH", "CASH SALE", "CASH SALES")


def _gate_pass_needs_full_page(g: dict, items: list) -> bool:
    """True when content will not fit cleanly on half A4 (~148mm) — print full page instead."""
    n = len(items or [])
    if n >= 5:
        return True
    # Approximate printed height in mm (header/party/meta/signatures ≈ 70–85mm fixed)
    height_mm = 78.0
    height_mm += n * 7.2
    if any(float(it.get("net_weight") or 0) for it in (items or [])):
        height_mm += 6.0  # Net Wt column + total weight line
    if _gate_pass_is_cash_sale(g):
        height_mm += 8.0 + n * 0.8  # Rate/Amount columns + amount totals
    inv_wt = float(g.get("invoice_weight_kg") or 0)
    phys = float(g.get("physical_weight_kg") or g.get("weight") or 0)
    if inv_wt or phys:
        height_mm += 14.0  # weight / variance block
    if _gate_pass_remarks_text(g):
        height_mm += 8.0
    if g.get("delivery_note_no") or g.get("grn_no"):
        height_mm += 6.0
    if g.get("driver_contact") or g.get("sales_invoice_no") or g.get("purchase_invoice_no"):
        height_mm += 4.0
    # Leave a small margin under 148mm so nothing clips
    return height_mm > 135.0


def _gate_pass_body(g: dict, items: list, *, duplicate: bool = False) -> str:
    """Build gate-pass HTML body (no page wrapper)."""
    inv_wt = float(g.get("invoice_weight_kg") or 0)
    phys = float(g.get("physical_weight_kg") or g.get("weight") or 0)
    var_kg = float(g.get("weight_variance_kg") or round(phys - inv_wt, 3))
    var_pct = float(g.get("weight_variance_pct") or 0)
    is_purchase = bool(g.get("purchase_invoice_id") or g.get("purchase_invoice_no"))
    show_amt = _gate_pass_is_cash_sale(g)
    extra = {
        "Type": (g.get("pass_type") or "").replace("_", " ").title(),
        "Vehicle": g.get("vehicle_no") or "—",
        "Driver": g.get("driver_name") or "—",
        "Weight Slip": g.get("weight_slip_no") or "—",
    }
    if g.get("driver_contact"):
        extra["Driver Contact"] = g.get("driver_contact")
    if g.get("sales_invoice_no"):
        extra["Sales Invoice"] = g["sales_invoice_no"]
    if g.get("purchase_invoice_no"):
        extra["Purchase Invoice"] = g["purchase_invoice_no"]
    party_phone = (g.get("party_phone") or g.get("customer_phone") or g.get("supplier_phone") or "").strip()
    if party_phone:
        extra["Party Contact"] = party_phone
    elif g.get("customer_id") or g.get("supplier_id"):
        extra["Party Contact"] = "—"

    title = "Gate Pass — DUPLICATE" if duplicate else ("Inward Gate Pass" if is_purchase else "Gate Pass")
    banner = '<div class="copy-banner gate-pass-dup-banner">DUPLICATE</div>' if duplicate else ""
    body = banner + _doc_header(
        title, g["document_no"], g["pass_date"], "Party", g.get("party_name"), extra,
        party_on_new_line=True,
        doc_time=g.get("pass_time") or g.get("created_at"),
    )
    if g.get("delivery_note_no"):
        body += _totals_block([f"<b>Delivery Note:</b> {escape(g['delivery_note_no'])}"])
    if g.get("grn_no"):
        body += _totals_block([f"<b>GRN:</b> {escape(g['grn_no'])}"])

    # Format line values on a shallow copy so dual print can reuse items
    lines = []
    has_wt = any(float(it.get("net_weight") or 0) for it in items)
    cols = [("item_code", "Code"), ("item_name", "Product"), ("quantity", "Qty")]
    if has_wt:
        cols.append(("net_weight", "Net Wt (kg)"))
    # Amounts only on SALE IN CASH / cash-sale gate passes (not credit / purchase)
    if show_amt:
        cols.extend([("rate", "Rate"), ("amount", "Amount")])
    total_qty = total_wt = total_amt = 0.0
    for src in items:
        it = dict(src)
        it["item_code"] = it.get("item_code") or "—"
        qty = float(it.get("quantity") or 0)
        nw = float(it.get("net_weight") or 0)
        it["quantity"] = f"{qty:,.2f}"
        it["net_weight"] = f"{nw:,.3f}"
        total_qty += qty
        total_wt += nw
        if show_amt:
            rate = float(src.get("rate") or 0)
            amt = float(src.get("amount") or 0)
            if not amt and rate and qty:
                amt = round(rate * qty, 2)
            it["rate"] = f"{rate:,.2f}"
            it["amount"] = f"{amt:,.2f}"
            total_amt += amt
        lines.append(it)
    if lines:
        body += _lines_table(lines, cols)
        summary = [f"<b>Total Quantity:</b> {total_qty:,.2f}"]
        if has_wt:
            summary.append(f"<b>Total Item Weight:</b> {total_wt:,.3f} kg")
        if show_amt:
            inv_total = _gate_pass_invoice_amount(g)
            summary.append(f"<b>Total Amount:</b> Rs. {total_amt:,.2f}")
            if inv_total and abs(inv_total - total_amt) > 0.05:
                summary.append(f"<b>Invoice Net:</b> Rs. {inv_total:,.2f}")
        body += _totals_block(summary)

    wt_lines = []
    if inv_wt:
        wt_lines.append(f"<b>Invoice Weight:</b> {inv_wt:,.3f} kg")
    if phys:
        wt_lines.append(f"<b>Physical Weight (Scale):</b> {phys:,.3f} kg")
    if inv_wt or phys:
        cls = "variance-ok" if abs(var_kg) < 0.5 else ("variance-warn" if abs(var_kg) < 5 else "variance-bad")
        wt_lines.append(f"<b>Variance:</b> <span class='{cls}'>{var_kg:+,.3f} kg ({var_pct:.2f}%)</span>")
    if wt_lines:
        body += _totals_block(wt_lines)

    remarks = _gate_pass_remarks_text(g)
    # Always print Remarks line on gate pass (especially purchase / inward)
    body += _totals_block([f"<b>Remarks:</b> {escape(remarks) if remarks else '—'}"])
    body += signature_block_html(doc_label="gate pass")
    return body


def _wrap_gate_pass_dual(original_body: str, duplicate_body: str, title: str) -> str:
    """Original + Duplicate on one A4 page (half + half)."""
    office = f'<div class="half-page-sheet"><div class="copy-banner">ORIGINAL</div>{original_body}</div>'
    dup = f'<div class="half-page-sheet">{duplicate_body}</div>'
    css = PRINT_CSS_PORTRAIT_HALF.replace(
        "</style>",
        f"{_VOUCHER_PRINT_CSS_EXTRA}"
        ".gate-pass-dup-banner { color: #b91c1c; border-color: #b91c1c; letter-spacing: .14em; }"
        "</style>",
    )
    inner = (
        f'<div class="voucher-dual-a4">{office}'
        f'<div class="half-page-cut dual-mid-cut">— — — CUT HERE — ORIGINAL / DUPLICATE — — —</div>'
        f"{dup}</div>"
    )
    return f"""<!DOCTYPE html><html><head><meta charset="utf-8"><title>{escape(title)}</title>
    {css}<script>function doPrint(){{window.print();}}</script></head><body class="voucher-dual-body">{inner}
    <p class="no-print"><button class="print-btn" onclick="doPrint()">Print (Original + Duplicate)</button></p>
    </body></html>"""


def gate_pass_html(pass_id, *, duplicate: bool = False, dual: bool = False):
    """Gate pass print — half A4 when it fits; full page when content is bigger than half."""
    from db_commercial import get_gate_pass_material_lines

    rows = [r for r in db.get_gate_passes() if r["id"] == pass_id]
    if not rows:
        return ""
    g = rows[0]
    items = get_gate_pass_material_lines(g)
    uid = document_preparer_user_id(g)
    footer = document_footer_html(uid)
    use_full = _gate_pass_needs_full_page(g, items)

    if dual:
        if use_full:
            return _wrap_gate_pass_multi_full(
                _gate_pass_body(g, items, duplicate=False),
                _gate_pass_body(g, items, duplicate=True),
                g["document_no"],
                uid,
            )
        orig = _gate_pass_body(g, items, duplicate=False) + footer
        dup = _gate_pass_body(g, items, duplicate=True) + footer
        return _wrap_gate_pass_dual(orig, dup, f"{g['document_no']} Original+Duplicate")

    body = _gate_pass_body(g, items, duplicate=duplicate)
    title = f"{g['document_no']} DUPLICATE" if duplicate else g["document_no"]
    if use_full:
        html = _wrap_doc(body, title, page_mode="full", user_id=uid)
    else:
        html = _wrap_doc(body, title, page_mode="half", user_id=uid)
        html = html.replace(
            "</style>",
            ".half-page-sheet { height: 148mm; max-height: 148mm; box-sizing: border-box; }</style>",
            1,
        )
    if duplicate:
        html = html.replace(
            "</style>",
            ".gate-pass-dup-banner { color: #b91c1c; border-color: #b91c1c; "
            "letter-spacing: .14em; font-size: 12px; }</style>",
            1,
        )
    return html


def _wrap_gate_pass_multi_full(original_body: str, duplicate_body: str, doc_no: str, user_id=None) -> str:
    """Original + Duplicate as two full A4 pages (for long multi-line gate passes)."""
    footer = document_footer_html(user_id)
    css = PRINT_CSS_PORTRAIT_FULL.replace(
        "</style>",
        f"{_VOUCHER_PRINT_CSS_EXTRA}"
        ".gate-pass-dup-banner { color: #b91c1c; border-color: #b91c1c; letter-spacing: .14em; }"
        ".gp-full-page { page-break-after: always; }"
        ".gp-full-page:last-child { page-break-after: auto; }"
        "</style>",
    )
    p1 = f'<div class="gp-full-page"><div class="copy-banner">ORIGINAL</div>{original_body}{footer}</div>'
    p2 = f'<div class="gp-full-page">{duplicate_body}{footer}</div>'
    return f"""<!DOCTYPE html><html><head><meta charset="utf-8"><title>{escape(doc_no)} Original+Duplicate</title>
    {css}<script>function doPrint(){{window.print();}}</script></head><body>{p1}{p2}
    <p class="no-print"><button class="print-btn" onclick="doPrint()">Print (Original + Duplicate)</button></p>
    </body></html>"""


def weight_slip_html(slip_id):
    try:
        import streamlit as st
        u = st.session_state.get("user")
        op = u.get("username") if u else None
    except Exception:
        op = None
    return db.weight_slip_print_html(slip_id, operator_name=op)


def finance_voucher_html(vch_source, entry_id):
    v = db.get_finance_voucher(vch_source, entry_id)
    if not v:
        return ""
    body, title, prepared_name, party_name = _finance_voucher_body(v)
    doc_title = v.get("document_no", title)
    if v.get("side") == "receipt":
        return _wrap_receipt_voucher_dual(body, doc_title, prepared_name, party_name)
    # Cash/Bank payment: top 50% of A4 only
    css = PRINT_CSS_PORTRAIT_HALF.replace(
        "</style>", f"{_VOUCHER_PRINT_CSS_EXTRA}</style>",
    )
    inner = _payment_voucher_half_inner(body, prepared_name, party_name)
    return f"""<!DOCTYPE html><html><head><meta charset="utf-8"><title>{escape(doc_title)}</title>
    {css}<script>function doPrint(){{window.print();}}</script></head><body>{inner}
    <p class="no-print"><button class="print-btn" onclick="doPrint()">Print</button></p></body></html>"""


def finance_vouchers_batch_html(entries):
    """Combine multiple cash/bank vouchers into one print job (one page each).

    entries: iterable of (vch_source, entry_id) or dicts with those keys / entry_source.
    """
    sheets = []
    titles = []
    for item in entries or []:
        if isinstance(item, dict):
            src = item.get("vch_source") or item.get("entry_source")
            eid = item.get("id") or item.get("entry_id")
        else:
            src, eid = item[0], item[1]
        if not src or eid is None:
            continue
        v = db.get_finance_voucher(src, int(eid))
        if not v:
            continue
        body, title, prepared_name, party_name = _finance_voucher_body(v)
        doc_no = v.get("document_no") or title
        titles.append(str(doc_no))
        if v.get("side") == "receipt":
            block = _receipt_voucher_dual_inner(body, prepared_name, party_name)
        else:
            block = _payment_voucher_half_inner(body, prepared_name, party_name)
        sheets.append(f'<div class="voucher-batch-page">{block}</div>')
    if not sheets:
        return ""
    doc_title = f"Cash Vouchers ({len(sheets)})"
    if len(titles) <= 4:
        doc_title = " + ".join(titles)
    css = PRINT_CSS_PORTRAIT_HALF.replace(
        "</style>",
        f"{_VOUCHER_PRINT_CSS_EXTRA}{_VOUCHER_BATCH_CSS}</style>",
    )
    inner = "\n".join(sheets)
    return f"""<!DOCTYPE html><html><head><meta charset="utf-8"><title>{escape(doc_title)}</title>
    {css}<script>function doPrint(){{window.print();}}</script></head>
    <body class="voucher-batch-body">{inner}
    <p class="no-print"><button class="print-btn" onclick="doPrint()">Print {len(sheets)} voucher(s)</button></p>
    </body></html>"""


def document_print_batch_toolbar(html, title, key_prefix="batch", *, preview_height=720):
    """Preview / download / open-print for a multi-document HTML bundle."""
    import streamlit as st
    import streamlit.components.v1 as components

    if not html:
        st.warning("No vouchers to print.")
        return
    with st.expander(f"Print Preview — {title}", expanded=True):
        components.html(html, height=preview_height, scrolling=True)
    c1, c2 = st.columns(2)
    safe = "".join(ch if ch.isalnum() or ch in "-_" else "_" for ch in title.lower())[:48]
    c1.download_button(
        "Download HTML", html.encode("utf-8"), f"{safe or 'vouchers'}.html", "text/html",
        key=f"{key_prefix}_h",
    )
    if c2.button("Open Print Dialog", key=f"{key_prefix}_pr", type="primary"):
        components.html(
            html.replace("</body>", "<script>window.onload=function(){window.print();}</script></body>"),
            height=0,
        )


def party_transfer_voucher_html(transfer_id):
    t = db.get_party_transfer(transfer_id)
    if not t:
        return ""
    title = "Party Transfer Voucher"
    try:
        from application.data_gateway import PARTY_TRANSFER_TYPES as PT
        label = PT.get(t["transfer_type"], t["transfer_type"])
    except Exception:
        label = t["transfer_type"]
    poster = document_poster_user_id(t)
    meta = {"Reference": t.get("reference_no") or "—"}
    if poster:
        pname = resolve_preparer_name(poster)
        if pname:
            meta["Posted By"] = pname
    body = _doc_header(
        title, t["document_no"], t["transfer_date"], "Transfer Type", label, meta,
        doc_time=t.get("created_at") or t.get("posted_at"),
    )
    body += f"<p><b>Description:</b> {escape(t.get('description') or '—')}</p>"
    body += _lines_table([{
        "from": f"{t.get('from_party_code','')} — {t.get('from_party_name','')}",
        "to": f"{t.get('to_party_code','')} — {t.get('to_party_name','')}",
        "amount": f"{float(t.get('amount', 0)):,.2f}",
    }], [("from", "Transfer From"), ("to", "Transfer To"), ("amount", "Amount (Rs.)")])
    body += _voucher_amount_box("Transfer Amount", t.get("amount", 0))
    body += signature_block_html(doc_label="voucher", style=PRINT_STYLE_POSTED, user_id=poster)
    return _wrap_doc(
        body, t["document_no"], user_id=poster, footer_label="Posted by",
    )


def expense_bill_html(bill_id):
    """Multi-expense bill: header + one row per expense head (no merged narration)."""
    b = db.get_expense_bill(bill_id)
    if not b:
        return ""
    poster = document_poster_user_id(b) or document_preparer_user_id(b)
    party_lbl = f"{b.get('party_code') or ''} — {b.get('party_name') or ''}".strip(" —")
    meta = {
        "Party Type": (b.get("party_type") or "").title(),
        "Settlement": (b.get("settlement") or "").title(),
        "Reference": b.get("reference_no") or "—",
    }
    if poster:
        pname = resolve_preparer_name(poster)
        if pname:
            meta["Posted By"] = pname
    body = _doc_header(
        "Expense Bill",
        b.get("document_no") or "",
        b.get("bill_date"),
        "Party",
        party_lbl or "—",
        meta,
        party_on_new_line=True,
        doc_time=b.get("created_at") or b.get("posted_at"),
    )
    note = (b.get("description") or "").strip()
    if note:
        body += f"<p><b>Bill note:</b> {escape(note)}</p>"
    rows = []
    for ln in b.get("lines") or []:
        code = ln.get("expense_code") or ""
        name = ln.get("expense_name") or ""
        narr = (ln.get("narration") or "").strip()
        rows.append({
            "account": f"{code} — {name}".strip(" —"),
            "narration": narr or "—",
            "amount": f"{float(ln.get('amount') or 0):,.2f}",
        })
    body += _lines_table(
        rows,
        [("account", "Expense Account"), ("narration", "Narration"), ("amount", "Amount (Rs.)")],
    )
    body += _voucher_amount_box("Bill Total", b.get("total_amount", 0))
    body += signature_block_html(doc_label="expense bill", style=PRINT_STYLE_POSTED, user_id=poster)
    return _wrap_doc(
        body, b.get("document_no") or "Expense Bill", user_id=poster, footer_label="Posted by",
        page_mode="full",
    )


def receipt_voucher_html(receipt_id, vch_source=None):
    if vch_source:
        return finance_voucher_html(vch_source, receipt_id)
    for src in ("cash_receipt", "bank_receipt"):
        html = finance_voucher_html(src, receipt_id)
        if html:
            return html
    return ""


def payment_voucher_html(payment_id, vch_source=None):
    if vch_source:
        return finance_voucher_html(vch_source, payment_id)
    for src in ("cash_payment", "bank_payment"):
        html = finance_voucher_html(src, payment_id)
        if html:
            return html
    return ""


def production_batch_html(prod_id):
    rows = [r for r in db.get_production_orders() if r["id"] == prod_id]
    if not rows:
        return ""
    p = rows[0]
    body = _doc_header(
        "Production Batch Sheet", p["document_no"], p["order_date"], "Product", p.get("product_name"),
        {"Planned": p.get("planned_qty"), "Actual": p.get("actual_qty"), "Wastage": p.get("wastage_qty"),
         "Cost/Unit": p.get("cost_per_unit"), "Status": p.get("status")},
        doc_time=p.get("created_at"),
    )
    body += signature_block_html(doc_label="production order")
    return _wrap_doc(body, p["document_no"], user_id=document_preparer_user_id(p))


PRINTERS = {
    "Sales Invoice": lambda i: sales_invoice_html(i, False),
    "Sales Tax Invoice": lambda i: sales_invoice_html(i, True),
    "Sale Return": sale_return_html,
    "Purchase Invoice": purchase_invoice_html,
    "Purchase Return": purchase_return_html,
    "Purchase Order": purchase_order_html,
    "Sales Order": sales_order_html,
    "Delivery Note": delivery_note_html,
    "GRN": grn_html,
    "Gate Pass": gate_pass_html,
    "Job Card": job_card_html,
    "Weight Slip": weight_slip_html,
    "Journal Voucher": journal_voucher_html,
    "Receipt Voucher": receipt_voucher_html,
    "Payment Voucher": payment_voucher_html,
    "Finance Voucher": finance_voucher_html,
    "Party Transfer": party_transfer_voucher_html,
    "Customer Receipt": lambda i, s=None: finance_voucher_html(s, i) if s else receipt_voucher_html(i),
    "Supplier Payment": lambda i, s=None: finance_voucher_html(s, i) if s else payment_voucher_html(i),
    "Expense Payment": lambda i, s=None: finance_voucher_html(s, i) if s else payment_voucher_html(i),
    "Expense Bill": expense_bill_html,
    "Production Batch Sheet": production_batch_html,
}


def document_print_toolbar(doc_type, doc_id, key_prefix="doc", vch_source=None, *, duplicate=False, dual=False, hide_rates=False):
    import streamlit as st
    import streamlit.components.v1 as components

    include_hdr = use_print_company_header_checkbox(key_prefix)
    with print_company_header_scope(include_hdr):
        if doc_type == "Party Transfer":
            html = party_transfer_voucher_html(doc_id)
        elif doc_type == "Expense Bill":
            html = expense_bill_html(doc_id)
        elif doc_type in ("Finance Voucher", "Customer Receipt", "Supplier Payment", "Expense Payment") and vch_source:
            html = finance_voucher_html(vch_source, doc_id)
        elif doc_type == "Receipt Voucher" and vch_source:
            html = finance_voucher_html(vch_source, doc_id)
        elif doc_type == "Payment Voucher" and vch_source:
            html = finance_voucher_html(vch_source, doc_id)
        elif doc_type == "Gate Pass":
            html = gate_pass_html(doc_id, duplicate=duplicate, dual=dual)
        elif doc_type == "Sales Order":
            html = sales_order_html(doc_id, hide_rates=bool(hide_rates))
        else:
            fn = PRINTERS.get(doc_type)
            if not fn:
                st.warning("Print format not available.")
                return
            html = fn(doc_id)
    if not html:
        st.warning("Document not found.")
        return

    preview_title = doc_type
    if dual:
        preview_title = f"{doc_type} (Original + Duplicate)"
    elif duplicate:
        preview_title = f"{doc_type} (Duplicate)"

    with st.expander(f"Print Preview — {preview_title}", expanded=True):
        # Long multi-line gate passes use full page — taller preview so all rows are visible
        if dual:
            preview_h = 900
        elif doc_type == "Gate Pass":
            preview_h = 780
        elif doc_type in (
            "Finance Voucher", "Receipt Voucher", "Payment Voucher",
            "Customer Receipt", "Supplier Payment", "Expense Payment",
        ):
            preview_h = 520
        else:
            preview_h = 560
        components.html(html, height=preview_h, scrolling=True)

    suffix = "_dual" if dual else ("_dup" if duplicate else "")
    fname = f"{doc_type.replace(' ', '_').lower()}_{doc_id}{suffix}"

    # Friendly PDF name: "Sale Order SO-0009 - Customer Name.pdf"
    party_name = ""
    pdf_label = doc_type
    try:
        if doc_type == "Sales Order":
            so = db.get_sales_order(int(doc_id))
            doc_no = ((so or {}).get("document_no") or "").strip()
            pdf_label = f"Sale Order {doc_no}".strip() if doc_no else "Sale Order"
            party_name = (so or {}).get("customer_name") or ""
        elif doc_type in ("Sales Invoice", "Sales Tax Invoice"):
            inv = db.get_sale(int(doc_id))
            doc_no = ((inv or {}).get("invoice_no") or (inv or {}).get("document_no") or "").strip()
            pdf_label = f"Sale Invoice {doc_no}".strip() if doc_no else "Sale Invoice"
            party_name = (inv or {}).get("customer_name") or ""
        elif doc_type == "Purchase Invoice":
            inv = db.get_purchase(int(doc_id)) if hasattr(db, "get_purchase") else None
            doc_no = ((inv or {}).get("invoice_no") or (inv or {}).get("document_no") or "").strip()
            pdf_label = f"Purchase Invoice {doc_no}".strip() if doc_no else "Purchase Invoice"
            party_name = (inv or {}).get("supplier_name") or ""
        elif doc_type == "Delivery Note" and hasattr(db, "get_delivery_note"):
            dn = db.get_delivery_note(int(doc_id))
            doc_no = ((dn or {}).get("document_no") or "").strip()
            pdf_label = f"Delivery Note {doc_no}".strip() if doc_no else "Delivery Note"
            party_name = (dn or {}).get("customer_name") or ""
    except Exception:
        party_name = ""
    from erp_ui.helpers import party_download_filename
    pdf_fname = party_download_filename(pdf_label, party_name, ext="pdf")
    if suffix:
        pdf_fname = pdf_fname.replace(".pdf", f"{suffix}.pdf")

    c1, c2, c3 = st.columns(3)
    c1.download_button("Print (HTML)", html.encode("utf-8"), f"{fname}.html", "text/html", key=f"{key_prefix}_h{suffix}")
    if c2.button("Open Print Dialog", key=f"{key_prefix}_pr{suffix}"):
        components.html(html.replace("</body>", "<script>window.onload=function(){window.print();}</script></body>"), height=0)
    pdf_bytes = None
    pdf_err = None
    try:
        if doc_type == "Sales Order" and not duplicate and not dual:
            pdf_bytes = sales_order_pdf_bytes(
                doc_id, hide_rates=bool(hide_rates), include_company=include_hdr,
            )
        elif doc_type in ("Sales Invoice", "Sales Tax Invoice") and not duplicate and not dual:
            pdf_bytes = sales_invoice_pdf_bytes(
                doc_id,
                tax_invoice=(doc_type == "Sales Tax Invoice"),
                include_company=include_hdr,
            )
        else:
            pdf_bytes = _scraped_html_pdf_bytes(
                html, preview_title, include_company=include_hdr,
            )
    except Exception as e:
        pdf_err = e
    if pdf_bytes:
        c3.download_button(
            "Download PDF",
            pdf_bytes,
            pdf_fname,
            "application/pdf",
            key=f"{key_prefix}_p{suffix}",
            type="primary",
        )
    else:
        c3.download_button(
            "Save HTML",
            html.encode("utf-8"),
            f"{fname}.html",
            "text/html",
            key=f"{key_prefix}_pf{suffix}",
        )
        if pdf_err:
            st.caption(f"PDF unavailable: {pdf_err}")

    # Gate Pass: one-click duplicate / dual print on the same screen
    if doc_type == "Gate Pass" and not duplicate and not dual:
        st.markdown("**Duplicate copy**")
        d1, d2 = st.columns(2)
        show_dup = d1.button("Print Duplicate", key=f"{key_prefix}_btn_dup", use_container_width=True)
        show_dual = d2.button(
            "Print Original + Duplicate (1 page)",
            key=f"{key_prefix}_btn_dual",
            use_container_width=True,
        )
        if show_dup:
            st.session_state[f"{key_prefix}_mode"] = "dup"
        if show_dual:
            st.session_state[f"{key_prefix}_mode"] = "dual"
        mode = st.session_state.get(f"{key_prefix}_mode")
        if mode == "dup":
            with print_company_header_scope(include_hdr):
                dup_html = gate_pass_html(doc_id, duplicate=True)
            st.success("Duplicate ready — use Open Print Dialog below, or the Print button inside the preview.")
            with st.expander("Print Preview — Gate Pass (Duplicate)", expanded=True):
                components.html(dup_html, height=560, scrolling=True)
            dd1, dd2, dd3 = st.columns(3)
            dd1.download_button(
                "Print Duplicate (HTML)", dup_html.encode("utf-8"),
                f"gate_pass_{doc_id}_dup.html", "text/html", key=f"{key_prefix}_dup_h",
            )
            if dd2.button("Open Print Dialog (Duplicate)", key=f"{key_prefix}_dup_pr"):
                components.html(
                    dup_html.replace("</body>", "<script>window.onload=function(){window.print();}</script></body>"),
                    height=0,
                )
            dd3.download_button(
                "Save Duplicate HTML", dup_html.encode("utf-8"),
                f"gate_pass_{doc_id}_dup.html", key=f"{key_prefix}_dup_pf",
            )
        elif mode == "dual":
            with print_company_header_scope(include_hdr):
                dual_html = gate_pass_html(doc_id, dual=True)
            st.success("Original + Duplicate on one A4 — use Open Print Dialog below.")
            with st.expander("Print Preview — Gate Pass (Original + Duplicate)", expanded=True):
                components.html(dual_html, height=720, scrolling=True)
            t1, t2, t3 = st.columns(3)
            t1.download_button(
                "Print Dual (HTML)", dual_html.encode("utf-8"),
                f"gate_pass_{doc_id}_dual.html", "text/html", key=f"{key_prefix}_dual_h",
            )
            if t2.button("Open Print Dialog (1 page)", key=f"{key_prefix}_dual_pr"):
                components.html(
                    dual_html.replace("</body>", "<script>window.onload=function(){window.print();}</script></body>"),
                    height=0,
                )
            t3.download_button(
                "Save Dual HTML", dual_html.encode("utf-8"),
                f"gate_pass_{doc_id}_dual.html", key=f"{key_prefix}_dual_pf",
            )
