version = 5.7.0
archive_dir = C:\MY ERPS\certs\config\archive\erp.ifschemicals.com
cert = C:\MY ERPS\certs\config\live\erp.ifschemicals.com\cert.pem
privkey = C:\MY ERPS\certs\config\live\erp.ifschemicals.com\privkey.pem
chain = C:\MY ERPS\certs\config\live\erp.ifschemicals.com\chain.pem
fullchain = C:\MY ERPS\certs\config\live\erp.ifschemicals.com\fullchain.pem
[renewalparams]
account = 50eaba05219c7b188f49e0b1d412181e
pref_challs = http-01,
config_dir = C:\MY ERPS\certs\config
work_dir = C:\MY ERPS\certs\work
logs_dir = C:\MY ERPS\certs\logs
authenticator = webroot
webroot_path = C:\MY ERPS\certs\acme-www,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
erp.ifschemicals.com = C:\MY ERPS\certs\acme-www
